// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../kue
//   ../express

import { Queue } from 'kue';
import { Job } from 'kue';
import * as express from 'express';

export interface IKueWorkerConfig {
    connection: {
        redis: string;
    };
}
export type KueWorkerSuccessfulTaskCallback = (task: Task, result: any) => void;
export type KueWorkerFailedTaskCallback = (task: Task, error: any) => void;
export class KueWorker {
    config: IKueWorkerConfig;
    jobQueue: Queue;
    constructor(config: IKueWorkerConfig);
    registerTasksForProcessing(taskTypes: Array<ITaskClass>, successCallback: KueWorkerSuccessfulTaskCallback, failCallback: KueWorkerFailedTaskCallback): void;
    registerTaskForProcessing(taskType: ITaskClass, successCallback: KueWorkerSuccessfulTaskCallback, failCallback: KueWorkerFailedTaskCallback): void;
}

export interface ITaskClass {
    name: string;
    maxConcurrent: number;
    workerConfig: IKueWorkerConfig;
    deserialize(serializedParams: any): Promise<Task>;
}
export abstract class Task {
    static maxConcurrent: number;
    static workerConfig: IKueWorkerConfig;
    protected job?: Job;
    abstract serialize(): any;
    abstract doTaskWork(): Promise<any>;
    submit(): Promise<{}>;
}

export class KueWorkerSubmitter {
    constructor(config: IKueWorkerConfig);
    getBrowserApp(): express.Application;
    registerTasksForSubmitting(taskTypes: Array<ITaskClass>): this;
    registerTaskForSubmitting(taskType: ITaskClass): this;
}

